---
- name: Install Nginx
  hosts: all
  # 获取sudo权限
  become: true
  tasks:
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present
    - name: Install Nginx repository
      yum:
        name: http://nginx.org/packages/centos/{{ansible_distribution_major_version}}/noarch/RPMS/nginx-release-centos-{{ansible_distribution_major_version}}-0.el{{ansible_distribution_major_version}}.ngx.noarch.rpm
        state: present
    - name: Install Nginx
      yum:
        name: nginx
        state: present
    - name: Start Nginx
      systemd:
        name: nginx
        state: started
        enabled: true